### ISSUE TITLE
Custom f-stop entries on lenses

### ISSUE THREAD

**Issue by classabbyamp** [tommi1hirvonen/ExifNotes#19]
**Is your feature request related to a problem? Please describe.**
I have a lens with a lower limit of f/3.8. this is not in the list provided

**Describe the solution you'd like**
Either f/3.8 being added to the list or free-text entry allowed

**Describe alternatives you've considered**
I currently use f/3.5 for that lens' lower limit

**Comment by AngelaDMerkel** [comment]
There is a small pencil icon in the frame entry which allows you to enter non-standard apertures. It's not an option that lenda itself to repetition, but it works.

**Comment by classabbyamp** [comment]
I'm talking about in the lens editing view, where you set the range of f-stops

**Comment by tommi1hirvonen** [comment]
Other people have been asking for this feature as well. I'm assuming the ability to enter custom aperture values per frame is simply not convenient enough when you use uncommon aperture values frequently. And that makes sense. If you have a lens with a largest aperture of say f/1.9, you might be wanting to use that pretty often. And then it would be just easier to select that from a predefined list of values instead of adding it manually every time.

I already have some ideas of how to maybe implement this with a relatively low amount of effort.

**Comment by fotopan** [comment]
I vote for additional custom f-stops - I have lenses with F1.7, F1.9 and F2.4 max. aperture values.
