### ISSUE TITLE
Ability to define negative and zero roll frame numbers

### ISSUE THREAD

**Issue by fotopan** [tommi1hirvonen/ExifNotes#26]
**Is your feature request related to a problem? Please describe.**
When I load a roll of film carefully  I routinely get exposures on frames before number 1 - these are numbered on the film itself like 00 (for frame before 0), 0 or similar. I can't see the way to note these frames in ExifNote so that the frame notes correspond to the roll frame numbers.

**Describe the solution you'd like**
I would like to be able to define frames for a roll of film - like to say that a contains exposures -1, 0, 1 and so on.

**Describe alternatives you've considered**
None so far.

**Additional context**

**Comment by tommi1hirvonen** [comment]
I can see where the need for this feature is coming from and in a way I have experienced it myself. When carefully loading a 36 frame roll, I can often squeeze 37 frames from it. I would guess though that there is practically no reason to have negative frame numbers beyond -1, -2, maybe -3. So if the app allowed selecting frame numbers from a range of -3..100 instead of the current 1..100, would that be a sufficient solution to this? Any thoughts? I have dealt with by just assigning the extra frame the number 37, but if you want the frame number to match that on the negative (e.g. 00), then having the frame number 0 available in the app too could be useful.

**Comment by fotopan** [comment]
If one could number frames from -3 to 100 (including 0) that would be really great and absolutely sufficient in the contex of frames before frame number 1. And, using negative numbers for frames before 0 is a good idea. 
BTW, my record is 39 exposures from 36 exposure roll: 00, 0, 1-36, E but usually I skip 00 so 38 frames (0, 1-36, E) is a norm for me (I am using mostly Fujifilm stock).

**Comment by fotopan** [comment]
Default for the first frame should be 1 as it is now so to not break existing habits I presume.

**Comment by tommi1hirvonen** [comment]
I agree to keeping 1 as the default starting number. Thanks for the additional input! I think the specs are clear enough now.
