### ISSUE TITLE
Export film roll is missing

### ISSUE THREAD

**Issue by mogol07** [tommi1hirvonen/ExifNotes#37]
**Describe the bug**
In last version (1.20.0) on Android I couldn't find "export roll" button / menu.
In previous interface it's quite obvious in Settings. But now I could export full DB or complimentary pictures only.
as I remember DB is required to backup or move information to another device (binary format). But roll's export is provide CSV and cmd for update properties of final images. And I couldn't find it.

Maybe it's not a bug, but just "new interface"...

**Expected behavior**
A button "Export roll" is located ideally in roll's settings.

**Device (please complete the following information):**
 - Poco F2 Pro
 - Android version: 12 (MIUI 13.0.8)
 - App version 1.20.0

**Comment by tommi1hirvonen** [comment]
The roll can be exported with the following steps in version 1.20.0 of Exif Notes. It is still very similar to previous versions.
- Click on the roll you wish export to navigate to its frames.
- At the bottom of the frames list view there is the share icon/button.
- Clicking on the share icon opens a popup menu with two options
  - Share files
  - Export files to storage
- Selecting either of these options opens a dialog where you can choose which files you want to export. Available options are
  - csv
  - ExifTool commands
  - JSON
- Select the formats you wish to export and click OK
- Depending on which share option you chose, you are either presented with different sharing options or a folder explorer to select a location on your device's storage.

So instead of the formats being defined in the app's settings they can now be selected on a roll-by-roll basis.

**Comment by mogol07** [comment]
Thanks! Now I found it.
If it was in release notes, I didn't read it carefully. 
Mea culpa!
